# # (c) Copyright 2022 Hewlett Packard Enterprise Development LP
# name: Bump version
# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         fetch-depth: '0'
#     - name: Bump version and push tag
#       run: ./.github/workflows/release.sh
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         WITH_V: true
#         DEFAULT_BUMP: patch
#         ACTION: release
