# (c) Copyright 2022 Hewlett Packard Enterprise Development LP
name: Validate Terraform
on: [push, pull_request]
jobs:
  Terraform_Validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -diff
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
