# (c) Copyright 2022 Hewlett Packard Enterprise Development LP
name: Validate Terraform
on: [push, pull_request]
jobs:
  Terraform_Validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -diff
      continue-on-error: true

     # Init and validate root directory
    - name: Terraform Init and Validate root directory
      id: init_and_validate
      run: terraform init && terraform validate -no-color

      # Init and validate sub directories
    - name: Terraform Init and Validate sub directories
      id: sub_init_and_validate
      run: tf_dirs="$(/usr/bin/find . -name "*.tf" | xargs -I{} dirname {} | uniq)"; for d in $tf_dirs; do pushd "$d" > /dev/null; echo $d; pwd; terraform init && terraform validate; popd > /dev/null; done
